#!/bin/bash
#-----------
source $NOTE_TOOL/include/checkDate
#--------------------------
date_str=$(date +'%Y/%m/%d')
time_str=""
#------------------
# Analyze Argments
for arg in $@
do
  res="$(checkDate $arg $date_str)" && \
  if [[ "$res" != "no_date" ]] ; then
    date_str="$res"
    continue
  fi
done
#-----------
cat "${NOTE_HOME}/cal/${date_str}"

