#!/bin/bash
#-----------
# $1     ... YYYY/MM/DD
# $2     ... HH:MM or ALLDAY
# ${*:3} ... Schdule
#--------------------------
source $NOTE_HOME/include/checkDate
#--------------------------
date_str=$(date +'%Y/%m/%d')
time_str=""
endtime_str=""
title_str=""
location_str=""
tags_str=""
#------------------
# Analyze Argments
for arg in $@
do
  res="$(checkDate $arg $date_str)" && \
  if [[ "$res" != "no_date" ]] ; then
    date_str="$res"
    continue
  fi ; if [[ "$arg" =~ ^[0-9]*:[0-9]*$ || "$arg" == "ALLDAY" ]] ; then
    time_str="$arg"
  fi
done
#-----------
get_file_path="${NOTE_HOME}/cal/${date_str}"

# Check Insert Line
get_line_number=1
get_file_line_number=$(wc -l $get_file_path | awk '{print $1}')
if [[ $get_file_line_number -ne 0 ]]
then
  insert_line_number=1
    def_time=$(date -d '-1 minutes' +'%s')
    next_exist=0
    while read line
    do
      time_str="$(echo $line | awk '{print $1}')"
      if [[ "$time_str" == "ALLDAY" ]]
      then
        continue
      fi

      if [[ $def_time -lt $(date -d "$1 $(echo $line | awk '{print $1}')" +'%s') ]]
      then
        echo $line
        next_exist=1
      fi
      ((get_line_number++))
    done < "$get_file_path" && \
    if [[ $next_exist -eq 0 ]]
    then
      echo "Todays Schdule was done."
    fi

else
  echo "No Scheduled."
fi
